// Code generated by <git repo>. DO NOT EDIT.
package deep

var Instance *deep

// <deep> from github.com/alh1m1k/gosingl/test/deep

func T0() error {
	return Instance.T0()
}

func Ilvl1() error {
	return Instance.il1.Ilvl1()
}
