// Code generated by <git repo>. DO NOT EDIT.
package deep

var Instance *deep

// <deep> from github.com/alh1m1k/gosingl/test/deep

func T0() error {
	return Instance.T0()
}

func Ilvl1() error {
	return Instance.il1.Ilvl1()
}

func Ilvl2() error {
	return Instance.il1.Ilvl2()
}

// <io.ByteScanner> from io

func UnreadByte() error {
	return Instance.il1.UnreadByte()
}

func Read(p []byte) (n int, err error) {
	return Instance.tl1.tl2.SectionReader.Read(p)
}

func Seek(offset int64, whence int) (int64, error) {
	return Instance.tl1.tl2.SectionReader.Seek(offset, whence)
}

func ReadAt(p []byte, off int64) (n int, err error) {
	return Instance.tl1.tl2.SectionReader.ReadAt(p, off)
}

func Size() int64 {
	return Instance.tl1.tl2.SectionReader.Size()
}

func ReadByte() (byte, error) {
	return Instance.il1.ReadByte()
}
