// Code generated by <git repo>. DO NOT EDIT.
package deep

var Instance *deep

func T0() error {
	return Instance.T0()
}

// <il1> from /home/alhimik/go/src/github.com/alh1m1k/gosingl/test/deep

func Ilvl1() error {
	return Instance.il1.Ilvl1()
}

// <tl1> from /home/alhimik/go/src/github.com/alh1m1k/gosingl/test/deep
