// Code generated by <git repo>. DO NOT EDIT.
package deep

var Instance *deep

func T0() error {
	return Instance.T0()
}

// <il1> from /home/alhimik/go/src/github.com/alh1m1k/gosingl/test/deep

func Ilvl1() error {
	return Instance.il1.Ilvl1()
}

// <tl1> from /home/alhimik/go/src/github.com/alh1m1k/gosingl/test/deep

// <il2> from /home/alhimik/go/src/github.com/alh1m1k/gosingl/test/deep

func Ilvl2() error {
	return Instance.Ilvl2()
}

// <tl2> from /home/alhimik/go/src/github.com/alh1m1k/gosingl/test/deep

// <io.ByteScanner> from /usr/local/go/src/io

func UnreadByte() error {
	return Instance.UnreadByte()
}

// <io.SectionReader> from /usr/local/go/src/io

func Read(p []byte) (n int, err error) {
	return Instance.SectionReader.Read(p)
}

func Seek(offset int64, whence int) (int64, error) {
	return Instance.SectionReader.Seek(offset, whence)
}

func ReadAt(p []byte, off int64) (n int, err error) {
	return Instance.SectionReader.ReadAt(p, off)
}

func Size() int64 {
	return Instance.SectionReader.Size()
}

// <ByteReader> from /usr/local/go/src/io

func ReadByte() (byte, error) {
	return Instance.ReadByte()
}
