// Code generated by <git repo>. DO NOT EDIT.
package interfaceValidation

var Instance *interfaceValidationValid1

// <interfaceValidationValid1> from github.com/alh1m1k/gosingl/test/interfaceValidation

func Write(p []byte) (n int, err error) {
	return Instance.Write(p)
}
