// Code generated by <git repo>. DO NOT EDIT.
package arraySliceType

var Instance _arraySlice_

// <_arraySlice_> from github.com/alh1m1k/gosingl/test/arraySliceType

func Proxy(p0 []<-chan int64) []chan<- int64 {
	return Instance.Proxy(p0)
}

func First(string2 []string) []rune {
	return Instance.First(string2)
}

func Ref(string2 *[]string, num *[5]int64) {
	Instance.Ref(string2, num)
}

func ArrayFunction(p0 [3]map[int]struct{}, p1 [5]map[int]struct{}) (multiple [3][5]map[int][]struct {
	ABC string
}, err error) {
	return Instance.ArrayFunction(p0, p1)
}
