// Code generated by <git repo>. DO NOT EDIT.
package generics

import "os"

var g generics[int, bool, *os.File]

// <generics> from github.com/alh1m1k/gosingl/test/generics

func Typed(a int, b bool) {
	g.Typed(a, b)
}

func InnerTyped(a int) {
	g.innerGenerics.InnerTyped(a)
}

func OverlapTyped(a float32) {
	g.overlapGenerics.OverlapTyped(a)
}

func LongCall(a int, b float32, c *os.File, d *os.File) {
	g.longType.LongCall(a, b, c, d)
}
