// Code generated by <git repo>. DO NOT EDIT.
package arrayTarget

import "unsafe"

var Instance arrayTarget

// <arrayTarget> from github.com/alh1m1k/gosingl/test/arrayTarget

func Showed(pointer unsafe.Pointer, p0 int, a, p1, c bool) error {
	return Instance.Showed(pointer, p0, a, p1, c)
}
