// Code generated by <git repo>. DO NOT EDIT.
package mapTarget

import "unsafe"

var Instance mapTarget

func Showed(pointer unsafe.Pointer, p0 int, a, p1, c bool) error {
	return Instance.Showed(pointer, p0, a, p1, c)
}
