// Code generated by <git repo>. DO NOT EDIT.
package split

var Instance *split

// <split> from github.com/alh1m1k/gosingl/test/split

func InterfaceEmpty(any2 any, bool2 bool, c int32, d interface{}, g *string) (string, error) {
	return Instance.InterfaceEmpty(any2, bool2, c, d, g)
}

func InterfaceMethods(any2 any, bool2 bool, c int32, d interface {
	doStuff(a string) error
}, g *string) (string, error) {
	return Instance.InterfaceMethods(any2, bool2, c, d, g)
}

func InterfaceMethodsDeep(any2 any, bool2 bool, c int32, d interface {
	IStuff(a string) error
	IStuff2(ifn interface {
		IStuffDeep(a string) error
	})
}, g *string) (string, error) {
	return Instance.InterfaceMethodsDeep(any2, bool2, c, d, g)
}

func Some() {
	Instance.Some()
}
